# Generated by Django 5.2.9 on 2025-12-03 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorInvitation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_invitations', to='api.project')),
            ],
            options={
                'db_table': 'collaborator_invitations',
                'unique_together': {('project', 'invited_user')},
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.collaboratorinvitation')),
            ],
            options={
                'db_table': 'collaborators',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
